[project]
name = "test-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
]

[tool.uv]
dev-dependencies = [
    "logging>=0.4.9.6",
    "pytest>=8.3.5",
    "ruff>=0.11.10",
]
